
import type { User, Issue, ProductionLine } from "@/lib/types";
import { subHours, subDays, subMinutes } from 'date-fns';

const now = new Date();

export const mockUsers: User[] = [
  {
    id: 'KbawAuA2mDZvk0JmWxM0lcyS5R52',
    firstName: 'Alex',
    lastName: 'Johnson',
    email: 'alex.johnson@andon.pro',
    role: 'admin',
    plan: 'pro',
    address: '123 Tech Avenue',
    country: 'US',
    phone: '555-0101',
  },
  {
    id: 'user-supervisor-01',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@andon.pro',
    role: 'supervisor',
    plan: 'pro',
    address: '456 Factory Rd',
    country: 'US',
    phone: '555-0102',
  },
  {
    id: 'user-operator-01',
    firstName: 'Bob',
    lastName: 'Williams',
    email: 'bob.williams@andon.pro',
    role: 'operator',
    plan: 'pro',
    productionLineId: 'line-a',
    address: '789 Assembly Ln',
    country: 'US',
    phone: '555-0103',
  },
   {
    id: 'user-operator-02',
    firstName: 'Alice',
    lastName: 'Jones',
    email: 'alice.jones@andon.pro',
    role: 'operator',
    plan: 'pro',
    productionLineId: 'line-b',
    address: '101 Component Ct',
    country: 'US',
    phone: '555-0104',
  },
];

export const mockProductionLines: ProductionLine[] = [
    { id: 'line-a', name: 'Assembly Line A', workstations: ['Station A1', 'Station A2', 'Station A3', 'QA Checkpoint A'] },
    { id: 'line-b', name: 'Packaging Line B', workstations: ['Station B1', 'Station B2', 'Labeling B', 'Final Inspection B'] },
    { id: 'line-c', name: 'Component Fabrication C', workstations: ['Cutting C1', 'Molding C2', 'Finishing C3'] },
];

export const mockIssues: Issue[] = [
  {
    id: 'issue-001',
    title: 'Network connection lost at Station A2',
    location: 'Assembly Line A - Station A2',
    productionLineId: 'line-a',
    priority: 'critical',
    status: 'in_progress',
    category: 'it',
    subCategory: 'network',
    reportedAt: subMinutes(now, 15),
    reportedBy: { name: 'Bob Williams', email: 'bob.williams@andon.pro' },
    productionStopped: true,
  },
  {
    id: 'issue-002',
    title: 'Material shortage for item #PN-54321',
    location: 'Assembly Line A - Station A1',
    productionLineId: 'line-a',
    priority: 'high',
    status: 'reported',
    category: 'logistics',
    subCategory: 'material-shortage',
    reportedAt: subHours(now, 1),
    reportedBy: { name: 'Bob Williams', email: 'bob.williams@andon.pro' },
    productionStopped: false,
    itemNumber: 'PN-54321',
    quantity: 50,
  },
  {
    id: 'issue-003',
    title: 'Torque wrench needs calibration',
    location: 'Packaging Line B - Station B1',
    productionLineId: 'line-b',
    priority: 'medium',
    status: 'reported',
    category: 'tool',
    subCategory: 'calibration',
    reportedAt: subHours(now, 4),
    reportedBy: { name: 'Alice Jones', email: 'alice.jones@andon.pro' },
    productionStopped: false,
  },
  {
    id: 'issue-004',
    title: 'Incorrect measurements on batch #789',
    location: 'QA Checkpoint A',
    productionLineId: 'line-a',
    priority: 'high',
    status: 'resolved',
    category: 'quality',
    subCategory: 'measurement',
    reportedAt: subHours(now, 8),
    reportedBy: { name: 'Bob Williams', email: 'bob.williams@andon.pro' },
    resolvedAt: subHours(now, 6),
    resolvedBy: { name: 'Jane Smith', email: 'jane.smith@andon.pro' },
    resolutionNotes: 'Re-calibrated the primary sensor and re-inspected the batch. All units now within tolerance.',
    productionStopped: true,
  },
  {
    id: 'issue-005',
    title: 'Operator needs assistance with new procedure',
    location: 'Packaging Line B - Labeling B',
    productionLineId: 'line-b',
    priority: 'low',
    status: 'resolved',
    category: 'assistance',
    reportedAt: subDays(now, 1),
    reportedBy: { name: 'Alice Jones', email: 'alice.jones@andon.pro' },
    resolvedAt: subDays(now, 1),
    resolvedBy: { name: 'Jane Smith', email: 'jane.smith@andon.pro' },
    resolutionNotes: 'Provided on-the-spot training for the new labeling software update.',
    productionStopped: false,
  },
];
